Add more tt10 things

diff --git a/.github/workflows/flow.yaml b/.github/workflows/flow.yaml
--- a/.github/workflows/flow.yaml
+++ b/.github/workflows/flow.yaml
@@ -116,8 +116,8 @@ jobs:
       - name: Prerequisitos de PNG
         uses: awalsh128/cache-apt-pkgs-action@latest
         with:
-          packages: librsvg2-bin pngquant # librsvg2-bin for rsvg-convert; pngquant for heavy PNG compression.
-          version: tt05 # I think naming a version builds a reusable packages cache for that name.
+          packages: librsvg2-bin pngquant ghdl-llvm # librsvg2-bin for rsvg-convert; pngquant for heavy PNG compression.
+          version: tt10 # I think naming a version builds a reusable packages cache for that name.
       
       - name: Usar Archivos de tiny tapeout
         uses: actions/checkout@v3
@@ -158,12 +158,99 @@ jobs:
         with:
           name: gds_render
           path: 'gds_render.png'
+          
   viewer:
     needs: Run
     runs-on: ubuntu-latest
     permissions:
-      pages: write      # to deploy to Pages
-      id-token: write   # to verify the deployment originates from an appropriate source
+      pages: write
+      id-token: write
     steps:
-      - uses: TinyTapeout/tt-gds-action/viewer@tt10
-
+      - name: Checkout GDS2glTF repo
+        uses: actions/checkout@v4
+        with:
+          repository: TinyTapeout/GDS2glTF
+          fetch-depth: 0
+  
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+          cache: 'pip'
+  
+      - name: Download GDS artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: GDS
+  
+      - name: Download gds_render (png) artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: gds_render
+          path: gh-pages
+          
+      - name: gds2gltf
+        shell: bash
+        run: |
+          pip install -r requirements.txt
+          if [ -f tt_submission/tool_versions.json ]; then
+            git checkout ihp-sg13g2
+          fi
+          cp tt_submission/*.gds tinytapeout.gds
+          python3 gds2gltf.py tinytapeout.gds
+          cp tinytapeout.gds.gltf gh-pages/tinytapeout.gds.gltf
+  
+      - name: Generate HTML pages that redirects to viewer
+        shell: bash
+        run: |
+          cat << EOF >> gh-pages/index.html
+            <!DOCTYPE html>
+            <html lang="en">
+            <head>
+              <meta charset="UTF-8">
+              <meta http-equiv="X-UA-Compatible" content="IE=edge">
+              <meta name="viewport" content="width=device-width, initial-scale=1.0">
+              <title>Redirecting to GDS Viewer...</title>
+            </head>
+            <body>
+              <script>
+                location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/tinytapeout.gds.gltf');
+              </script>
+            </body>
+            </html>
+          EOF
+  
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: 'gh-pages'
+  
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
+  
+      - name: Check for failure
+        if: failure()
+        shell: bash
+        run: |
+          echo "Failed to deploy to GitHub Pages, please follow the link to troubleshoot: https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part"
+  
+          cat << EOF >> $GITHUB_STEP_SUMMARY
+          # Error
+          Failed to deploy to GitHub Pages. [Click here for instructions how to fix](https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part).
+          EOF
+  
+          exit 1
+  
+      - name: Display preview in workflow summary
+        shell: bash
+        run: |
+          PAGE_URL=${{ steps.deployment.outputs.page_url }}
+          PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
+          cat << EOF >> $GITHUB_STEP_SUMMARY
+          # 3D Viewer
+          [open 3D viewer](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)
+  
+          # 2D Preview
+          ![png]($PAGE_URL/gds_render.png)
+          EOF
